# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/programowanie/projekty/ProgramowanieObiektowe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/programowanie/projekty/ProgramowanieObiektowe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/programowanie/projekty/ProgramowanieObiektowe/CMakeFiles /data/programowanie/projekty/ProgramowanieObiektowe//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/programowanie/projekty/ProgramowanieObiektowe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProgramowanieObiektowe.out

# Build rule for target.
ProgramowanieObiektowe.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProgramowanieObiektowe.out
.PHONY : ProgramowanieObiektowe.out

# fast build rule for target.
ProgramowanieObiektowe.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/build
.PHONY : ProgramowanieObiektowe.out/fast

ProgramowanieObiektowe/arkusz/cell/intCell.o: ProgramowanieObiektowe/arkusz/cell/intCell.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/cell/intCell.o

# target to build an object file
ProgramowanieObiektowe/arkusz/cell/intCell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/cell/intCell.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/cell/intCell.cpp.o

ProgramowanieObiektowe/arkusz/cell/intCell.i: ProgramowanieObiektowe/arkusz/cell/intCell.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/cell/intCell.i

# target to preprocess a source file
ProgramowanieObiektowe/arkusz/cell/intCell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/cell/intCell.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/cell/intCell.cpp.i

ProgramowanieObiektowe/arkusz/cell/intCell.s: ProgramowanieObiektowe/arkusz/cell/intCell.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/cell/intCell.s

# target to generate assembly for a file
ProgramowanieObiektowe/arkusz/cell/intCell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/cell/intCell.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/cell/intCell.cpp.s

ProgramowanieObiektowe/arkusz/cell/numericCell.o: ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/cell/numericCell.o

# target to build an object file
ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.o

ProgramowanieObiektowe/arkusz/cell/numericCell.i: ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/cell/numericCell.i

# target to preprocess a source file
ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.i

ProgramowanieObiektowe/arkusz/cell/numericCell.s: ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/cell/numericCell.s

# target to generate assembly for a file
ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/cell/numericCell.cpp.s

ProgramowanieObiektowe/arkusz/cell/stringCell.o: ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/cell/stringCell.o

# target to build an object file
ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.o

ProgramowanieObiektowe/arkusz/cell/stringCell.i: ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/cell/stringCell.i

# target to preprocess a source file
ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.i

ProgramowanieObiektowe/arkusz/cell/stringCell.s: ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/cell/stringCell.s

# target to generate assembly for a file
ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/cell/stringCell.cpp.s

ProgramowanieObiektowe/arkusz/column/column.o: ProgramowanieObiektowe/arkusz/column/column.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/column/column.o

# target to build an object file
ProgramowanieObiektowe/arkusz/column/column.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/column/column.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/column/column.cpp.o

ProgramowanieObiektowe/arkusz/column/column.i: ProgramowanieObiektowe/arkusz/column/column.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/column/column.i

# target to preprocess a source file
ProgramowanieObiektowe/arkusz/column/column.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/column/column.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/column/column.cpp.i

ProgramowanieObiektowe/arkusz/column/column.s: ProgramowanieObiektowe/arkusz/column/column.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/column/column.s

# target to generate assembly for a file
ProgramowanieObiektowe/arkusz/column/column.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/column/column.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/column/column.cpp.s

ProgramowanieObiektowe/arkusz/tablica/tablica.o: ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica.o

# target to build an object file
ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.o

ProgramowanieObiektowe/arkusz/tablica/tablica.i: ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica.i

# target to preprocess a source file
ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.i

ProgramowanieObiektowe/arkusz/tablica/tablica.s: ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica.s

# target to generate assembly for a file
ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica.cpp.s

ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.o: ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.o

# target to build an object file
ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.o
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.o

ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.i: ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.i

# target to preprocess a source file
ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.i
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.i

ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.s: ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.s

# target to generate assembly for a file
ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.s
.PHONY : ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.cpp.s

ProgramowanieObiektowe/io/fileOperations.o: ProgramowanieObiektowe/io/fileOperations.cpp.o
.PHONY : ProgramowanieObiektowe/io/fileOperations.o

# target to build an object file
ProgramowanieObiektowe/io/fileOperations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/io/fileOperations.cpp.o
.PHONY : ProgramowanieObiektowe/io/fileOperations.cpp.o

ProgramowanieObiektowe/io/fileOperations.i: ProgramowanieObiektowe/io/fileOperations.cpp.i
.PHONY : ProgramowanieObiektowe/io/fileOperations.i

# target to preprocess a source file
ProgramowanieObiektowe/io/fileOperations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/io/fileOperations.cpp.i
.PHONY : ProgramowanieObiektowe/io/fileOperations.cpp.i

ProgramowanieObiektowe/io/fileOperations.s: ProgramowanieObiektowe/io/fileOperations.cpp.s
.PHONY : ProgramowanieObiektowe/io/fileOperations.s

# target to generate assembly for a file
ProgramowanieObiektowe/io/fileOperations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/io/fileOperations.cpp.s
.PHONY : ProgramowanieObiektowe/io/fileOperations.cpp.s

ProgramowanieObiektowe/main.o: ProgramowanieObiektowe/main.cpp.o
.PHONY : ProgramowanieObiektowe/main.o

# target to build an object file
ProgramowanieObiektowe/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/main.cpp.o
.PHONY : ProgramowanieObiektowe/main.cpp.o

ProgramowanieObiektowe/main.i: ProgramowanieObiektowe/main.cpp.i
.PHONY : ProgramowanieObiektowe/main.i

# target to preprocess a source file
ProgramowanieObiektowe/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/main.cpp.i
.PHONY : ProgramowanieObiektowe/main.cpp.i

ProgramowanieObiektowe/main.s: ProgramowanieObiektowe/main.cpp.s
.PHONY : ProgramowanieObiektowe/main.s

# target to generate assembly for a file
ProgramowanieObiektowe/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/main.cpp.s
.PHONY : ProgramowanieObiektowe/main.cpp.s

ProgramowanieObiektowe/menu/menu.o: ProgramowanieObiektowe/menu/menu.cpp.o
.PHONY : ProgramowanieObiektowe/menu/menu.o

# target to build an object file
ProgramowanieObiektowe/menu/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/menu/menu.cpp.o
.PHONY : ProgramowanieObiektowe/menu/menu.cpp.o

ProgramowanieObiektowe/menu/menu.i: ProgramowanieObiektowe/menu/menu.cpp.i
.PHONY : ProgramowanieObiektowe/menu/menu.i

# target to preprocess a source file
ProgramowanieObiektowe/menu/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/menu/menu.cpp.i
.PHONY : ProgramowanieObiektowe/menu/menu.cpp.i

ProgramowanieObiektowe/menu/menu.s: ProgramowanieObiektowe/menu/menu.cpp.s
.PHONY : ProgramowanieObiektowe/menu/menu.s

# target to generate assembly for a file
ProgramowanieObiektowe/menu/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/menu/menu.cpp.s
.PHONY : ProgramowanieObiektowe/menu/menu.cpp.s

ProgramowanieObiektowe/operacje/operacje.o: ProgramowanieObiektowe/operacje/operacje.cpp.o
.PHONY : ProgramowanieObiektowe/operacje/operacje.o

# target to build an object file
ProgramowanieObiektowe/operacje/operacje.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/operacje/operacje.cpp.o
.PHONY : ProgramowanieObiektowe/operacje/operacje.cpp.o

ProgramowanieObiektowe/operacje/operacje.i: ProgramowanieObiektowe/operacje/operacje.cpp.i
.PHONY : ProgramowanieObiektowe/operacje/operacje.i

# target to preprocess a source file
ProgramowanieObiektowe/operacje/operacje.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/operacje/operacje.cpp.i
.PHONY : ProgramowanieObiektowe/operacje/operacje.cpp.i

ProgramowanieObiektowe/operacje/operacje.s: ProgramowanieObiektowe/operacje/operacje.cpp.s
.PHONY : ProgramowanieObiektowe/operacje/operacje.s

# target to generate assembly for a file
ProgramowanieObiektowe/operacje/operacje.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/operacje/operacje.cpp.s
.PHONY : ProgramowanieObiektowe/operacje/operacje.cpp.s

ProgramowanieObiektowe/utility/utility.o: ProgramowanieObiektowe/utility/utility.cpp.o
.PHONY : ProgramowanieObiektowe/utility/utility.o

# target to build an object file
ProgramowanieObiektowe/utility/utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/utility/utility.cpp.o
.PHONY : ProgramowanieObiektowe/utility/utility.cpp.o

ProgramowanieObiektowe/utility/utility.i: ProgramowanieObiektowe/utility/utility.cpp.i
.PHONY : ProgramowanieObiektowe/utility/utility.i

# target to preprocess a source file
ProgramowanieObiektowe/utility/utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/utility/utility.cpp.i
.PHONY : ProgramowanieObiektowe/utility/utility.cpp.i

ProgramowanieObiektowe/utility/utility.s: ProgramowanieObiektowe/utility/utility.cpp.s
.PHONY : ProgramowanieObiektowe/utility/utility.s

# target to generate assembly for a file
ProgramowanieObiektowe/utility/utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgramowanieObiektowe.out.dir/build.make CMakeFiles/ProgramowanieObiektowe.out.dir/ProgramowanieObiektowe/utility/utility.cpp.s
.PHONY : ProgramowanieObiektowe/utility/utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ProgramowanieObiektowe.out"
	@echo "... ProgramowanieObiektowe/arkusz/cell/intCell.o"
	@echo "... ProgramowanieObiektowe/arkusz/cell/intCell.i"
	@echo "... ProgramowanieObiektowe/arkusz/cell/intCell.s"
	@echo "... ProgramowanieObiektowe/arkusz/cell/numericCell.o"
	@echo "... ProgramowanieObiektowe/arkusz/cell/numericCell.i"
	@echo "... ProgramowanieObiektowe/arkusz/cell/numericCell.s"
	@echo "... ProgramowanieObiektowe/arkusz/cell/stringCell.o"
	@echo "... ProgramowanieObiektowe/arkusz/cell/stringCell.i"
	@echo "... ProgramowanieObiektowe/arkusz/cell/stringCell.s"
	@echo "... ProgramowanieObiektowe/arkusz/column/column.o"
	@echo "... ProgramowanieObiektowe/arkusz/column/column.i"
	@echo "... ProgramowanieObiektowe/arkusz/column/column.s"
	@echo "... ProgramowanieObiektowe/arkusz/tablica/tablica.o"
	@echo "... ProgramowanieObiektowe/arkusz/tablica/tablica.i"
	@echo "... ProgramowanieObiektowe/arkusz/tablica/tablica.s"
	@echo "... ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.o"
	@echo "... ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.i"
	@echo "... ProgramowanieObiektowe/arkusz/tablica/tablica_wysw.s"
	@echo "... ProgramowanieObiektowe/io/fileOperations.o"
	@echo "... ProgramowanieObiektowe/io/fileOperations.i"
	@echo "... ProgramowanieObiektowe/io/fileOperations.s"
	@echo "... ProgramowanieObiektowe/main.o"
	@echo "... ProgramowanieObiektowe/main.i"
	@echo "... ProgramowanieObiektowe/main.s"
	@echo "... ProgramowanieObiektowe/menu/menu.o"
	@echo "... ProgramowanieObiektowe/menu/menu.i"
	@echo "... ProgramowanieObiektowe/menu/menu.s"
	@echo "... ProgramowanieObiektowe/operacje/operacje.o"
	@echo "... ProgramowanieObiektowe/operacje/operacje.i"
	@echo "... ProgramowanieObiektowe/operacje/operacje.s"
	@echo "... ProgramowanieObiektowe/utility/utility.o"
	@echo "... ProgramowanieObiektowe/utility/utility.i"
	@echo "... ProgramowanieObiektowe/utility/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

